//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin_MySQL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class capdo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public capdo()
        {
            this.merchants = new HashSet<merchant>();
        }
    
        public long capdo_id { get; set; }
        public string tencapdo { get; set; }
        public long muckhuyenmaiquangcao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<merchant> merchants { get; set; }
    }
}
