//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin_MySQL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public customer()
        {
            this.hoadonmuas = new HashSet<hoadonmua>();
            this.merchants = new HashSet<merchant>();
            this.danhgias = new HashSet<danhgia>();
        }
    
        public long customer_id { get; set; }
        public string username { get; set; }
        public string salt { get; set; }
        public string password { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> ngaydangky { get; set; }
        public long tienao { get; set; }
        public Nullable<bool> tinhtrangkichhoat { get; set; }
        public string hoten { get; set; }
        public Nullable<System.DateTime> ngaysinh { get; set; }
        public string sodienthoai { get; set; }
        public Nullable<bool> gioitinh { get; set; }
        public string diachi { get; set; }
        public Nullable<bool> ismechant { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hoadonmua> hoadonmuas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<merchant> merchants { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<danhgia> danhgias { get; set; }
    }
}
