//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin_MySQL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hoadonban
    {
        public long hoadonban_id { get; set; }
        public Nullable<System.DateTime> ngaytao { get; set; }
        public Nullable<System.DateTime> ngayhoanthanh { get; set; }
        public string noigui { get; set; }
        public Nullable<long> soluong { get; set; }
        public Nullable<long> sanpham_id { get; set; }
        public Nullable<long> merchant_id { get; set; }
        public Nullable<long> hinhthucthanhtoan_id { get; set; }
        public Nullable<long> tinhtranggiaohang_id { get; set; }
        public Nullable<long> hoadonmua_id { get; set; }
        public Nullable<long> mausac_id { get; set; }
    
        public virtual hinhthucthanhtoan hinhthucthanhtoan { get; set; }
        public virtual sanpham sanpham { get; set; }
        public virtual merchant merchant { get; set; }
        public virtual tinhtranggiaohang tinhtranggiaohang { get; set; }
        public virtual hoadonmua hoadonmua { get; set; }
        public virtual mausac mausac { get; set; }
    }
}
