//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin_MySQL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sanpham_thongsokythuat
    {
        public long sanpham_id { get; set; }
        public long thongsokythuat_id { get; set; }
        public string giatri { get; set; }
    
        public virtual sanpham sanpham { get; set; }
        public virtual thongsokythuat thongsokythuat { get; set; }
    }
}
